import React, { useEffect, useRef, useState, type ReactNode, type CSSProperties } from 'react';
import { faqs, pages, steps } from './content';

type LayoutProps = { children: ReactNode; className?: string };
export function Container({ children, className = '' }: LayoutProps) { return <div className={`container ${className}`}>{children}</div>; }
export function Section({ children, className = '', id }: LayoutProps & { id: string }) { return <section id={id} className={`section ${className}`}><Container>{children}</Container></section>; }
export function Badge({ children }: LayoutProps) { return <span className="badge">{children}</span>; }
export function Card({ children, className = '' }: LayoutProps) { return <div className={`card ${className}`}>{children}</div>; }
export function Button({ children, href, secondary = false }: { children: ReactNode; href: string; secondary?: boolean }) { return <a className={`button ${secondary ? 'secondary' : ''}`} href={href}>{children}</a>; }
function Brand({ base }: { base: string }) { return <a className="brand" href={base}><img src={`${base}brand-mark.svg`} width="44" height="44" alt=""/><span>Écoute Moi<span className="brand-caption">ЗНАКОМСТВО НАЧИНАЕТСЯ С ГОЛОСА</span></span></a>; }
export function Navigation({ base }: { base: string }) {
  const [open, setOpen] = useState(false);
  const menuButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape' && open) { setOpen(false); menuButton.current?.focus(); } }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [open]);
  return <header className="header"><Container className="header-inner"><Brand base={base}/><button ref={menuButton} className="menu-toggle" aria-expanded={open} aria-controls="navigation" onClick={() => setOpen(!open)}>{open ? 'Закрыть ×' : 'Меню ☰'}</button><nav id="navigation" aria-label="Основная навигация" className={open ? 'nav open' : 'nav'}>{[['about', 'О проекте'], ['how', 'Как это работает'], ['safety', 'Безопасность'], ['faq', 'FAQ']].map(([id, label]) => <a key={id} href={`${base}#${id}`} onClick={() => setOpen(false)}>{label}</a>)}<a className="nav-cta" href={`${base}#download`} onClick={() => setOpen(false)}>Скоро <span aria-hidden="true">↗</span></a></nav></Container></header>;
}
export function Footer({ base }: { base: string }) { return <footer className="footer"><Container><div className="footer-top"><Brand base={base}/><p>Слушать. Слышать. Видеть.</p></div><div className="footer-links">{Object.entries(pages).map(([path, label]) => <a key={path} href={`${base}${path.slice(1)}/`}>{label}</a>)}</div><div className="footer-bottom"><span>© Écoute Moi, 2026</span><span>ecoutemoi.ru</span><span>Для совершеннолетних · 18+</span></div></Container></footer>; }
function Wave({ variant = '' }: { variant?: string }) { return <div className={`wave ${variant}`} aria-hidden="true">{Array.from({ length: 55 }, (_, i) => <i key={i} style={{ '--h': `${13 + Math.pow(Math.sin(i * 1.63), 2) * (18 + 70 * Math.pow(Math.sin(i / 54 * Math.PI), 2))}%`, '--delay': `${(i % 13) * -.17}s` } as CSSProperties}/> )}</div>; }
function VoiceArtwork() {
  const [paused, setPaused] = useState(false);
  return <div className={`voice-art ${paused ? 'paused' : ''}`}><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="art-top"><span className="signal-dot"/> ПЕРВОЕ ВПЕЧАТЛЕНИЕ — ГОЛОС</div><div className="art-center"><span className="art-eyebrow">У каждого голоса</span><Wave/><span className="art-serif">своя история.</span></div><div className="art-bottom"><span>ГОЛОС <b>→</b> РЕЗОНАНС</span><button onClick={() => setPaused(!paused)} aria-label={paused ? 'Включить анимацию волны' : 'Приостановить анимацию волны'} aria-pressed={paused}>{paused ? '▷' : 'Ⅱ'}</button></div></div>;
}
export function FlowStep({ index, title, body }: { index: number; title: string; body: string }) { return <li className="flow-step"><span className="step-number">0{index + 1}</span><div><h3>{title}</h3><p>{body}</p></div></li>; }
export function FAQItem({ question, answer }: { question: string; answer: string }) { return <details className="faq-item"><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>; }
function Home({ base }: { base: string }) { return <>
  <section className="hero"><Container><div className="hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="line"/> ЗНАКОМСТВА В ДРУГОМ РИТМЕ <span className="age">18+</span></div><h1>Слушать.<br/>Слышать.<br/><em>Видеть.</em></h1><p className="hero-lead">Знакомства, которые<br className="desktop-break"/> начинаются с голоса.</p><p className="hero-description">Écoute Moi помогает сначала услышать человека — его голос, интонацию и мысли. Анкета и фотографии появляются позже, когда интерес становится взаимным.</p><div className="hero-actions"><Button href={`${base}#download`}>Скоро в App Store <span aria-hidden="true">↗</span></Button><span>Android — позже</span></div></div><VoiceArtwork/></div><div className="hero-foot"><span>СНАЧАЛА УСЛЫШАТЬ. ПОТОМ УВИДЕТЬ.</span><a href="#about">Знакомьтесь с Écoute Moi <span aria-hidden="true">↓</span></a></div></Container></section>
  <Section id="about" className="about"><div className="section-label">01 / ДРУГОЕ ПЕРВОЕ ВПЕЧАТЛЕНИЕ</div><div className="split"><h2>Сначала<br/><em>голос.</em></h2><div className="section-copy"><p className="large-copy">Как человек смеётся.<br/>О чём говорит с увлечением.<br/>Какие слова выбирает.</p><p>В голосе есть то, чего не расскажет фотография. Интонация, мысли, манера общения — возможность заметить человека ещё до того, как вы его увидите.</p><a className="text-link" href="#how">От первого слова к знакомству <span aria-hidden="true">↗</span></a></div></div></Section>
  <Section id="how" className="how"><div className="section-label">02 / КАК ЭТО РАБОТАЕТ</div><div className="section-heading"><h2>Ближе.<br/><em>Шаг за шагом.</em></h2><p>Знакомство раскрывается постепенно.<br/>Каждый следующий шаг — по взаимному желанию.</p></div><ol className="flow">{steps.map(([title, body], index) => <FlowStep key={title} {...{ index, title, body }}/>)}</ol></Section>
  <Section id="attention" className="attention"><div className="attention-symbol" aria-hidden="true">“</div><h2>Меньше свайпов.<br/>Больше внимания<br/><em>человеку.</em></h2><p>Écoute Moi предлагает другой сценарий знакомства:<br/>сначала голос, потом визуальная часть.<br/>С пространством для интереса и осознанного выбора.</p></Section>
  <Section id="resonance" className="resonance"><div className="resonance-art" aria-hidden="true"><div/><div/><span>↔</span></div><div className="resonance-copy"><div className="section-label">03 / ТОТ САМЫЙ ОТКЛИК</div><h2>Это взаимно.<br/>Это <em>Резонанс.</em></h2><p>Вы услышали друг друга. И оба захотели узнать больше. Два Отклика становятся Резонансом — моментом, когда открываются анкеты и фотографии.</p><p>А дальше вы решаете, продолжать ли знакомство. Когда оба выбирают «да», появляется Взаимность и открывается чат.</p></div></Section>
  <Section id="safety"><div className="section-label">04 / ВАШИ ГРАНИЦЫ ИМЕЮТ ЗНАЧЕНИЕ</div><div className="section-heading"><h2>Приватность<br/>и <em>безопасность.</em></h2><p>Знакомиться — в своём темпе.<br/>Решать, с кем продолжать, — самостоятельно.</p></div><div className="safety-grid">{[['◎', 'Постепенное раскрытие', 'Анкета и фотографии открываются после взаимного Отклика. Не раньше.'], ['⊘', 'Контроль общения', 'Вы можете заблокировать пользователя или прекратить знакомство.'], ['⚑', 'Возможность пожаловаться', 'Жалобы доступны на этапе аудиописьма и в разговоре. Обращения предусмотрены для рассмотрения модерацией.']].map(([icon, heading, body]) => <Card key={heading}><span className="card-icon" aria-hidden="true">{icon}</span><h3>{heading}</h3><p>{body}</p></Card>)}</div><p className="safety-note">Забота о приватности — часть продукта. При этом ни один онлайн-сервис не может гарантировать абсолютную безопасность.</p></Section>
  <Section id="plans" className="plans"><div><div className="section-label">05 / ВАШ ФОРМАТ ЗНАКОМСТВА</div><h2>Больше<br/><em>возможностей.</em></h2><p>Дополнительные возможности для тех, кто хочет больше контроля и комфорта.</p></div><div className="plan-grid">{['Premium', 'Exclusive'].map((plan, index) => <Card key={plan} className={`plan plan-${index}`}><span className="plan-symbol" aria-hidden="true">{index ? '✳' : '✧'}</span><Badge>В БУДУЩЕМ</Badge><h3>{plan}</h3><p>Подробнее — скоро</p></Card>)}</div></Section>
  <Section id="download" className="download"><div className="section-label">СКОРО УСЛЫШИМСЯ</div><h2>Ваше знакомство<br/>начнётся <em>с голоса.</em></h2><p>Écoute Moi готовится к запуску.<br/>Ссылки на скачивание появятся здесь после публикации.</p><div className="store-grid">{[['iOS', 'App Store', 'Скоро'], ['ANDROID', 'Google Play', 'Скоро'], ['ANDROID', 'RuStore', 'Планируется']].map(([system, store, status]) => <Card className="store" key={store}><span className="store-system">{system}</span><h3>{store}</h3><Badge>{status}</Badge></Card>)}</div><span className="download-age">Только для пользователей 18+</span></Section>
  <Section id="faq" className="faq"><div><div className="section-label">ОСТАЛОСЬ ИНТЕРЕСНОЕ</div><h2>Давайте<br/><em>разберёмся.</em></h2><p>О голосе, взаимности<br/>и ваших возможностях.</p><a className="text-link" href={`${base}support/`}>Поддержка <span aria-hidden="true">↗</span></a></div><div className="faq-list">{faqs.map(([question, answer]) => <FAQItem key={question} {...{ question, answer }}/>)}</div></Section>
</>; }
function DocumentPage({ path, base }: { path: string; base: string }) {
  const known = Object.hasOwn(pages, path);
  return <section className="document"><Container><a className="text-link" href={base}>← На главную</a><div className="section-label">ÉCOUTE MOI / {known ? 'ИНФОРМАЦИЯ' : '404'}</div><h1>{pages[path] || 'Здесь пока тихо.'}</h1>{path === '/account-deletion' ? <><p className="document-lead">Вы можете удалить аккаунт в приложении.</p><ol className="document-steps"><li>Откройте профиль и найдите «Удалить аккаунт» внизу экрана.</li><li>Подтвердите действие. Начнётся трёхминутный таймер.</li><li>В течение этого времени удаление можно отменить.</li></ol><h2>Запросы по вашим данным</h2><p>Обратитесь через обратную связь в приложении. Публичный способ обращения без доступа к аккаунту находится в подготовке.</p><p>Информация о сроках удаления и исключениях хранения будет опубликована в <a href={`${base}privacy/`}>политике конфиденциальности</a>.</p></> : path === '/support' ? <><p className="document-lead">Поддержка доступна через приложение.</p><p>Откройте профиль, затем раздел безопасности и поддержки в центре управления аккаунтом. Выберите обращение в поддержку.</p><h2>Если нет доступа к аккаунту</h2><p>Публичный канал связи находится в подготовке. Контакт появится здесь после подтверждения.</p><p>Чтобы пожаловаться на конкретного пользователя, используйте раздел безопасности разговора. Также можно пожаловаться на аудиописьмо до открытия чата.</p></> : known ? <><Badge>В ПОДГОТОВКЕ</Badge><p className="document-lead">Документ находится в подготовке.</p><p>Утверждённая версия будет размещена на этой странице.</p></> : <><p className="document-lead">Страница не найдена.</p><p>Проверьте адрес или вернитесь к знакомству с Écoute Moi.</p><Button href={base}>На главную ↗</Button></>}</Container></section>;
}
export function App({ path = '/', base = '/' }: { path?: string; base?: string }) { return <React.Fragment><a className="skip-link" href="#main">Перейти к содержимому</a><Navigation base={base}/><main id="main">{path === '/' ? <Home base={base}/> : <DocumentPage {...{ path, base }}/>}</main><Footer base={base}/></React.Fragment>; }
